### ISSUE TITLE
Why babel?

### ISSUE THREAD

**Issue by styfle** [infernojs/inferno-typescript-example#5]
I was surprised to see references to babel in the `package.json`.
If you are using typescript (which supports JSX to JS transformation), why use babel at all?

**Comment by styfle** [comment]
For comparison, my [react-server-example-tsx](https://github.com/styfle/react-server-example-tsx/) does not use bable.

**Comment by MKGaru** [comment]
I made without babel example [here](/MKGaru/inferno-typescript-example)

**Comment by Havunen** [comment]
@MKGaru how does it work without `babel-plugin-inferno` ? that compiles divs into Inferno specific `createVNode` calls

**Comment by MKGaru** [comment]
@Havunen with createElement ( inferno-create-element ) and transpile jsx:react by typescript

**Comment by Havunen** [comment]
Okay keep in mind createElement is isomorphic and createVNode is monomorphic, this has significant difference in perf. Maybe we should write `jsx:inferno` to reduce overhead.

**Comment by Havunen** [comment]
Happy news!

Typescript 2.3 will ship support for custom transformers. I think we could create inferno-jsx-typescript plugin to transform jsx into createVNodes instead of createElement. 

:)

https://github.com/Microsoft/TypeScript/pull/13940

**Comment by Havunen** [comment]
This was btw delayed till 2.4 due to bugs in their API...

**Comment by styfle** [comment]
@Havunen I'm not familiar with the custom transformers, but TS 2.4 landed a week ago.

**Comment by Havunen** [comment]
Btw. Initial work for custom TSX compiler is done! Have a look: https://github.com/infernojs/inferno/issues/1154 but it needs testing! :)

**Comment by Havunen** [comment]
babel 7 has support for typescript so this is the recommended way now.

**Comment by Havunen** [comment]
This PR now removes babel: https://github.com/infernojs/inferno-typescript-example/pull/18
