### ISSUE TITLE
Inferno Router

### ISSUE THREAD

**Issue by thdxr** [infernojs/inferno-typescript-example#6]
If I attempt to import `inferno-router` I get "Cannot find module inferno-router" - any ideas?

**Comment by rodrigomb81** [comment]
Adding `moduleResolution: "node"` to `compilerOptions` in your tsconfig.json should make it work. For some reason without that option tsc can't find any packages (except inferno and inferno-component)

**Comment by thdxr** [comment]
Thanks! Figured it out earlier but yeah fixed my problem. Other thing to
consider is to change the jsx option to React and set the jsxFactory
function to createElement. Without this I wasn't able to actually use
inferno router

**Comment by rodrigomb81** [comment]
I'll keep it in mind. Right now I'm having problems using inferno-redux, tsc is complaining about some missing property on inferno-component. I think it might be because that dep is locked to version ^1.
