### ISSUE TITLE
Value-based element properties are not type-checked

### ISSUE THREAD

**Issue by abirmingham** [infernojs/inferno-typescript-example#8]
The properties of the value-based element Incrementer do not appear to be type-checked in index.tsx. To reproduce this issue:
1. Run npm start
2. Update index.tsx to contain <Incrementer name={0} />
3. Note that TS compiler does not complain that a number has been used when a string is needed

I'm not sure if this is a limitation of TypeScript, Inferno, or the specific configuration in this example project. It would be great to understand how to fix it though :)

**Comment by Havunen** [comment]
`npm run check` now does the type checking
